# Ocuda Travis CI Docker build file

os: linux
dist: trusty
sudo: required

language: bash

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker info

script:
  - docker build -f Dockerfile_ops -t ops .
  - docker build -f Dockerfile_promenade -t promenade .
