# Ocuda Travis CI Docker build file

os: linux
dist: xenial

language: bash

git:
  depth: 1

services:
  - docker

env:
  - TRAVISCI_DOCKERFILE=Dockerfile_ops BLD_DOCKER_IMAGE=ops
  - TRAVISCI_DOCKERFILE=Dockerfile_promenade BLD_DOCKER_IMAGE=promenade

script: env BLD_DOCKERFILE=$TRAVISCI_DOCKERFILE bash docker-build.bash
