# Ocuda Travis CI Docker build file

os: linux
dist: xenial

language: bash

git:
  depth: 1

services:
  - docker

env:
  - TCI_DOCKERFILE=Dockerfile_ops
  - TCI_DOCKERFILE=Dockerfile_promenade

script: env BLD_DOCKERFILE="$TCI_DOCKERFILE" bash docker-build.bash
