name: "Build - action"

on: [push, pull_request]

jobs:
  ops:
    name: "Ops Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build.bash
        env:
          BLD_DOCKER_IMAGE: ops
          BLD_DOCKERFILE: Dockerfile_ops
          CR_PASSWORD: ${{secrets.CR_PASSWORD}}
          CR_USER: ${{secrets.CR_USER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash

  promenade:
    name: "Promenade Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build.bash
        env:
          BLD_DOCKER_IMAGE: promenade
          BLD_DOCKERFILE: Dockerfile_promenade
          CR_PASSWORD: ${{secrets.CR_PASSWORD}}
          CR_USER: ${{secrets.CR_USER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash
