name: clean up containers
run-name: ${{ github.actor }} is cleaning up containers

on:
  schedule:
    - cron: "10 5 * * 5"
  workflow_dispatch:

jobs:
  clean-up-ops-containers:
    name: ghcr.io cleanup ops action
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        delete-untagged: true
        package: ops
  
  clean-up-promenade-containers:
    name: ghcr.io cleanup promenade action
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: dataaxiom/ghcr-cleanup-action@v1
      with:
        delete-untagged: true
        package: promenade

