name: CI

on: [push, pull_request]

jobs:
  ops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Docker image name
      run: echo ::set-env name=BLD_DOCKER_IMAGE::$GITHUB_REPOSITORY/${PWD##*/}

    - name: Extract Docker username
      run: echo ::set-env name=BLD_DOCKER_USERNAME::$(echo $GITHUB_REPOSITORY | cut -d/ -f1)

    - name: Run docker-build.bash
      env:
        BLD_DOCKER_HOST: docker.pkg.github.com
        BLD_DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        BLD_DOCKER_IMAGE: ops
      run: ./docker-build.bash

  promenade:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Docker image name
      run: echo ::set-env name=BLD_DOCKER_IMAGE::$GITHUB_REPOSITORY/${PWD##*/}

    - name: Extract Docker username
      run: echo ::set-env name=BLD_DOCKER_USERNAME::$(echo $GITHUB_REPOSITORY | cut -d/ -f1)

    - name: Run docker-build.bash
      env:
        BLD_DOCKER_HOST: docker.pkg.github.com
        BLD_DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        BLD_DOCKER_IMAGE: promenade
      run: ./docker-build.bash
